apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: motivational-quote-task
spec:
  results:
    - name: quote
      description: The motivational quote
      type: string
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!/bin/sh
        echo "Hello World!"
        echo "This is my first Tekton Task step!"

    - name: quote
      image: curlimages/curl:latest
      script: |
        apk add --no-cache jq
        curl -s https://v1.hitokoto.cn/?c=i | jq '.hitokoto' > $(results.quote.path)
      securityContext:
        runAsUser: 0