apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world-task
spec:
  description: |
    A simple task that echoes "Hello World" to demonstrate how Tekton Tasks work.
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi-minimal:latest
      script: |
        #!/bin/sh
        echo "Hello World!"
        echo "This is my first Tekton Task step!"
