apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: daily-info-run
spec:
  pipelineRef:
    name: daily-info-pipeline
  workspaces:
    - name: pipeline-output
      persistentVolumeClaim:
        claimName: my-pvc